server:
  port: 8083
spring:
  datasource:
    url: jdbc:mariadb://10.10.10.10:3306/test0518
    driver-class-name: org.mariadb.jdbc.Driver
    username: kks0518
    password: qwer1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
